### ISSUE TITLE
link to documentation is broken

### ISSUE THREAD

**Issue by mathisonian** [bokeh/bokeh-scala#16]
In the README the link to stable documentation gives an s3 access denied error:
https://s3.amazonaws.com/bokeh-scala/docs/2.11/0.3/index.html
![s3 broken](http://i.gif.fm/FQfUM.png)

**Comment by mattpap** [comment]
Thanks for reporting this. It looks like there is an issue with upload script.

**Comment by mattpap** [comment]
Actually it was just an issue with release procedure. bokeh-scala 0.4 was released and link to documentation is now alive.
